namespace EmployeesManager
{
    partial class FormFirstTimeLogin
    {

        private System.ComponentModel.IContainer components = null;




        #region Code generated by Windows Forms Designer


        /// <summary>
        // A method is needed to get the designer.There is no change
        /// The contents of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormFirstTimeLogin));
            this.panel_ = new System.Windows.Forms.Panel();
            this.Mainpanelform = new System.Windows.Forms.Panel();
            this.btnback = new System.Windows.Forms.Button();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.btnreset = new System.Windows.Forms.Button();
            this.btnlogin = new System.Windows.Forms.Button();
            this.txtpassword = new System.Windows.Forms.TextBox();
            this.txtusername = new System.Windows.Forms.TextBox();
            this.txtpasswordlabel = new System.Windows.Forms.Label();
            this.txtusernamelabel = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.fulldate = new System.Windows.Forms.Label();
            this.Hour = new System.Windows.Forms.Label();
            this.PanelMainTitle = new System.Windows.Forms.Panel();
            this.pictureBox8 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.btnNormal = new System.Windows.Forms.Button();
            this.btnMinimizar = new System.Windows.Forms.Button();
            this.btnMaximizar = new System.Windows.Forms.Button();
            this.btnExit = new System.Windows.Forms.Button();
            this.tmFullhourdisplay = new System.Windows.Forms.Timer(this.components);
            this.label5 = new System.Windows.Forms.Label();
            this.panel_.SuspendLayout();
            this.Mainpanelform.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.panel1.SuspendLayout();
            this.PanelMainTitle.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).BeginInit();
            this.SuspendLayout();
            // 
            // panel_
            // 
            this.panel_.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(69)))), ((int)(((byte)(76)))));
            this.panel_.Controls.Add(this.Mainpanelform);
            this.panel_.Controls.Add(this.panel1);
            this.panel_.Controls.Add(this.PanelMainTitle);
            this.panel_.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel_.Location = new System.Drawing.Point(0, 0);
            this.panel_.Name = "panel_";
            this.panel_.Size = new System.Drawing.Size(1100, 600);
            this.panel_.TabIndex = 0;
            // 
            // Mainpanelform
            // 
            this.Mainpanelform.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(69)))), ((int)(((byte)(76)))));
            this.Mainpanelform.Controls.Add(this.label5);
            this.Mainpanelform.Controls.Add(this.btnback);
            this.Mainpanelform.Controls.Add(this.pictureBox1);
            this.Mainpanelform.Controls.Add(this.btnreset);
            this.Mainpanelform.Controls.Add(this.btnlogin);
            this.Mainpanelform.Controls.Add(this.txtpassword);
            this.Mainpanelform.Controls.Add(this.txtusername);
            this.Mainpanelform.Controls.Add(this.txtpasswordlabel);
            this.Mainpanelform.Controls.Add(this.txtusernamelabel);
            this.Mainpanelform.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Mainpanelform.Location = new System.Drawing.Point(0, 43);
            this.Mainpanelform.Name = "Mainpanelform";
            this.Mainpanelform.Size = new System.Drawing.Size(1100, 457);
            this.Mainpanelform.TabIndex = 6;
            // 
            // btnback
            // 
            this.btnback.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(61)))), ((int)(((byte)(92)))));
            this.btnback.FlatAppearance.BorderSize = 0;
            this.btnback.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnback.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnback.ForeColor = System.Drawing.Color.White;
            this.btnback.Location = new System.Drawing.Point(936, 334);
            this.btnback.Name = "btnback";
            this.btnback.Size = new System.Drawing.Size(100, 35);
            this.btnback.TabIndex = 19;
            this.btnback.Text = "Back to login";
            this.btnback.UseVisualStyleBackColor = false;
            this.btnback.Click += new System.EventHandler(this.btnback_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::EmployeesManager.Properties.Resources.logo;
            this.pictureBox1.Location = new System.Drawing.Point(56, 68);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(409, 301);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 18;
            this.pictureBox1.TabStop = false;
            // 
            // btnreset
            // 
            this.btnreset.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(61)))), ((int)(((byte)(92)))));
            this.btnreset.FlatAppearance.BorderSize = 0;
            this.btnreset.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnreset.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnreset.ForeColor = System.Drawing.Color.White;
            this.btnreset.Location = new System.Drawing.Point(830, 334);
            this.btnreset.Name = "btnreset";
            this.btnreset.Size = new System.Drawing.Size(100, 35);
            this.btnreset.TabIndex = 15;
            this.btnreset.Text = "Reset";
            this.btnreset.UseVisualStyleBackColor = false;
            this.btnreset.Click += new System.EventHandler(this.btnreset_Click);
            // 
            // btnlogin
            // 
            this.btnlogin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(61)))), ((int)(((byte)(92)))));
            this.btnlogin.FlatAppearance.BorderSize = 0;
            this.btnlogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnlogin.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnlogin.ForeColor = System.Drawing.Color.White;
            this.btnlogin.Location = new System.Drawing.Point(724, 334);
            this.btnlogin.Name = "btnlogin";
            this.btnlogin.Size = new System.Drawing.Size(100, 35);
            this.btnlogin.TabIndex = 13;
            this.btnlogin.Text = "Login";
            this.btnlogin.UseVisualStyleBackColor = false;
            this.btnlogin.Click += new System.EventHandler(this.btnlogin_Click);
            // 
            // txtpassword
            // 
            this.txtpassword.Location = new System.Drawing.Point(842, 204);
            this.txtpassword.Multiline = true;
            this.txtpassword.Name = "txtpassword";
            this.txtpassword.PasswordChar = '*';
            this.txtpassword.Size = new System.Drawing.Size(224, 30);
            this.txtpassword.TabIndex = 4;
            // 
            // txtusername
            // 
            this.txtusername.Location = new System.Drawing.Point(842, 148);
            this.txtusername.Multiline = true;
            this.txtusername.Name = "txtusername";
            this.txtusername.Size = new System.Drawing.Size(224, 30);
            this.txtusername.TabIndex = 3;
            // 
            // txtpasswordlabel
            // 
            this.txtpasswordlabel.AutoSize = true;
            this.txtpasswordlabel.Font = new System.Drawing.Font("Montserrat", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtpasswordlabel.ForeColor = System.Drawing.Color.White;
            this.txtpasswordlabel.Location = new System.Drawing.Point(601, 197);
            this.txtpasswordlabel.Name = "txtpasswordlabel";
            this.txtpasswordlabel.Size = new System.Drawing.Size(235, 37);
            this.txtpasswordlabel.TabIndex = 1;
            this.txtpasswordlabel.Text = "New Password:";
            // 
            // txtusernamelabel
            // 
            this.txtusernamelabel.AutoSize = true;
            this.txtusernamelabel.Font = new System.Drawing.Font("Montserrat", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtusernamelabel.ForeColor = System.Drawing.Color.White;
            this.txtusernamelabel.Location = new System.Drawing.Point(667, 141);
            this.txtusernamelabel.Name = "txtusernamelabel";
            this.txtusernamelabel.Size = new System.Drawing.Size(169, 37);
            this.txtusernamelabel.TabIndex = 0;
            this.txtusernamelabel.Text = "Username:";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(55)))), ((int)(((byte)(61)))), ((int)(((byte)(69)))));
            this.panel1.Controls.Add(this.fulldate);
            this.panel1.Controls.Add(this.Hour);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(0, 500);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1100, 100);
            this.panel1.TabIndex = 5;
            // 
            // fulldate
            // 
            this.fulldate.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.fulldate.AutoSize = true;
            this.fulldate.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(128)));
            this.fulldate.ForeColor = System.Drawing.Color.White;
            this.fulldate.Location = new System.Drawing.Point(838, 71);
            this.fulldate.Name = "fulldate";
            this.fulldate.Size = new System.Drawing.Size(218, 20);
            this.fulldate.TabIndex = 4;
            this.fulldate.Text = "Monday, September 26, 2022";
            // 
            // Hour
            // 
            this.Hour.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.Hour.AutoSize = true;
            this.Hour.Font = new System.Drawing.Font("Microsoft Sans Serif", 35.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Hour.ForeColor = System.Drawing.Color.LightGray;
            this.Hour.Location = new System.Drawing.Point(842, 11);
            this.Hour.Name = "Hour";
            this.Hour.Size = new System.Drawing.Size(205, 54);
            this.Hour.TabIndex = 1;
            this.Hour.Text = "22:00:00";
            // 
            // PanelMainTitle
            // 
            this.PanelMainTitle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(61)))), ((int)(((byte)(92)))));
            this.PanelMainTitle.Controls.Add(this.pictureBox8);
            this.PanelMainTitle.Controls.Add(this.label1);
            this.PanelMainTitle.Controls.Add(this.btnNormal);
            this.PanelMainTitle.Controls.Add(this.btnMinimizar);
            this.PanelMainTitle.Controls.Add(this.btnMaximizar);
            this.PanelMainTitle.Controls.Add(this.btnExit);
            this.PanelMainTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.PanelMainTitle.Location = new System.Drawing.Point(0, 0);
            this.PanelMainTitle.Name = "PanelMainTitle";
            this.PanelMainTitle.Size = new System.Drawing.Size(1100, 43);
            this.PanelMainTitle.TabIndex = 1;
            this.PanelMainTitle.MouseDown += new System.Windows.Forms.MouseEventHandler(this.PanelMainTitle_MouseDown);
            // 
            // pictureBox8
            // 
            this.pictureBox8.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox8.Image")));
            this.pictureBox8.Location = new System.Drawing.Point(9, 9);
            this.pictureBox8.Name = "pictureBox8";
            this.pictureBox8.Size = new System.Drawing.Size(28, 28);
            this.pictureBox8.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox8.TabIndex = 5;
            this.pictureBox8.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Montserrat", 9.749999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(43, 13);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(119, 18);
            this.label1.TabIndex = 4;
            this.label1.Text = "Project Manager ";
            // 
            // btnNormal
            // 
            this.btnNormal.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnNormal.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnNormal.FlatAppearance.BorderSize = 0;
            this.btnNormal.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnNormal.Image = global::EmployeesManager.Properties.Resources.Normal;
            this.btnNormal.Location = new System.Drawing.Point(996, 0);
            this.btnNormal.Name = "btnNormal";
            this.btnNormal.Size = new System.Drawing.Size(43, 43);
            this.btnNormal.TabIndex = 3;
            this.btnNormal.UseVisualStyleBackColor = true;
            this.btnNormal.Visible = false;
            this.btnNormal.Click += new System.EventHandler(this.btnNormal_Click);
            // 
            // btnMinimizar
            // 
            this.btnMinimizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnMinimizar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnMinimizar.FlatAppearance.BorderSize = 0;
            this.btnMinimizar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMinimizar.Image = global::EmployeesManager.Properties.Resources.Minimize;
            this.btnMinimizar.Location = new System.Drawing.Point(950, 0);
            this.btnMinimizar.Name = "btnMinimizar";
            this.btnMinimizar.Size = new System.Drawing.Size(43, 43);
            this.btnMinimizar.TabIndex = 2;
            this.btnMinimizar.UseVisualStyleBackColor = true;
            this.btnMinimizar.Click += new System.EventHandler(this.btnMinimizar_Click);
            // 
            // btnMaximizar
            // 
            this.btnMaximizar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnMaximizar.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnMaximizar.FlatAppearance.BorderSize = 0;
            this.btnMaximizar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMaximizar.Image = global::EmployeesManager.Properties.Resources.maximize3;
            this.btnMaximizar.Location = new System.Drawing.Point(996, 0);
            this.btnMaximizar.Name = "btnMaximizar";
            this.btnMaximizar.Size = new System.Drawing.Size(43, 43);
            this.btnMaximizar.TabIndex = 1;
            this.btnMaximizar.UseVisualStyleBackColor = true;
            this.btnMaximizar.Click += new System.EventHandler(this.btnMaximizar_Click);
            // 
            // btnExit
            // 
            this.btnExit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnExit.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnExit.FlatAppearance.BorderSize = 0;
            this.btnExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExit.Image = global::EmployeesManager.Properties.Resources.Close;
            this.btnExit.Location = new System.Drawing.Point(1043, 2);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(39, 39);
            this.btnExit.TabIndex = 0;
            this.btnExit.UseVisualStyleBackColor = true;
            this.btnExit.Click += new System.EventHandler(this.btnexit_Click);
            // 
            // tmFullhourdisplay
            // 
            this.tmFullhourdisplay.Enabled = true;
            this.tmFullhourdisplay.Tick += new System.EventHandler(this.tmFullhourdislay_Tick);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(656, 267);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(362, 13);
            this.label5.TabIndex = 20;
            this.label5.Text = "* Pay Notice that you cannot change the Passowrd if you already have one";
            // 
            // FormFirstTimeLogin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 600);
            this.Controls.Add(this.panel_);
            this.DoubleBuffered = true;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(680, 500);
            this.Name = "FormFirstTimeLogin";
            this.Opacity = 0.95D;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.FormHome_Load);
            this.panel_.ResumeLayout(false);
            this.Mainpanelform.ResumeLayout(false);
            this.Mainpanelform.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.PanelMainTitle.ResumeLayout(false);
            this.PanelMainTitle.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel_;
        private System.Windows.Forms.Panel PanelMainTitle;
        private System.Windows.Forms.PictureBox pictureBox8;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnNormal;
        private System.Windows.Forms.Button btnMinimizar;
        private System.Windows.Forms.Button btnMaximizar;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Panel Mainpanelform;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label fulldate;
        private System.Windows.Forms.Label Hour;
        private System.Windows.Forms.Timer tmFullhourdisplay;
        private System.Windows.Forms.TextBox txtpassword;
        private System.Windows.Forms.Label txtpasswordlabel;
        private System.Windows.Forms.Button btnlogin;
        private System.Windows.Forms.Button btnreset;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.TextBox txtusername;
        private System.Windows.Forms.Label txtusernamelabel;
        private System.Windows.Forms.Button btnback;
        private System.Windows.Forms.Label label5;
    }
}

